name: ZACKY's Laboratory
description: 北九州市立大学でプログラミングを教えている山崎進のブログです。
url: https://zacky1972.github.io
kramdown:
  input: GFM
github: [Repository metadata]
exclude: ["vendor", "Gemfile", "Gemfile.lock"]
